trigger:
- main   # pipeline runs on main branch

pool:
  vmImage: ubuntu-latest

steps:
# Checkout code from GitHub
- checkout: self

# Archive your HTML files
- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(System.DefaultWorkingDirectory)/myapp'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    replaceExistingArchive: true

# Publish the zipped artifact
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'

# Deploy to Azure Web App
- task: AzureWebApp@1
  inputs:
    azureSubscription: 'my-azure-connection'
    appName: 'demo-webapp-12345'
    package: '$(Build.ArtifactStagingDirectory)/*.zip'
