trigger:
- main   # pipeline runs when you push to main branch

pool:
  vmImage: ubuntu-latest

steps:
# Checkout code from GitHub
- task: Checkout@1

# Archive your HTML files
- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    replaceExistingArchive: true

# Publish the zipped artifact (so it can be deployed)
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'

# Deploy to Azure Web App
- task: AzureWebApp@1
  inputs:
    azureSubscription: 'my-azure-connection'   # created service connection to Azure
    appName: 'demo-webapp-12345'                        # your Azure Web App name
    package: '$(Build.ArtifactStagingDirectory)/*.zip'
